
include/tweetnacl.hrl: c_src/header_scrape.c
	echo '%% Generated by Makefile from c_src/tweetnacl.h' \
	> include/tweetnacl.hrl &&    \
	gcc -E c_src/header_scrape.c  \
	| grep '^void scrape' -A 1000 \
	| grep '^f("'                 \
	| sed 's/^f("/-define(/'      \
	| sed 's/",/, /'              \
    | sed 's/);/)./'              \
	| sed 's/crypto_//'           \
	>> include/tweetnacl.hrl
